apiVersion: v1
kind: Service
metadata:
  name: opensdcp-git-db-service
spec:
  selector:
    app: opensdcp-git-db
    tier: backend
    track: stable
  ports:
    - name: db
      targetPort: db
      port: 5432
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opensdcp-git-db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opensdcp-git-db
        tier: backend
        track: stable
    spec:
      containers:
        - image: postgres:9.6
          name: db
          ports:
            - name: db
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: opensdcp-git-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: opensdcp-git-config
                  key: postgres_password
            - name: POSTGRES_DB
              value: gitea

# kubectl create configmap opensdcp-git-config \
# --from-literal=postgres_user=YOUR_USERNAME_HERE \
# --from-literal=postgres_password=YOUR_PASSWORD_HERE \

# enter "opensdcp-git-db-service" as the DB host in gitea install data